### Get all books
GET http://localhost:3000/books
Accept: application/json

### Get random book
GET http://localhost:3000/books/random
Accept: application/json

### Create book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Children of Dune",
  "published": "2019-06-04",
  "isbn": "9780593098240",
  "price": 15,
  "pic": "images/duneChildren.jpg",
  "authorId": 2
}

### Update existing book (replace id with real)
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Children of Dune",
  "published": "2019-06-04",
  "isbn": "9780593098240",
  "price": 18,
  "pic": "images/duneChildren.jpg",
  "authorId": 2
}

### Delete book (replace id with a real)
DELETE http://localhost:3000/books/11


### Get all authors
GET http://localhost:3000/authors
Accept: application/json

### Create author
POST http://localhost:3000/authors
Content-Type: application/json

{
  "name": "Ted Chiang",
  "bio": "Author of Arrival."
}

### Update existing author (replace id with real)
PUT http://localhost:3000/authors/2
Content-Type: application/json

{
  "name": "Frank Herbert",
  "bio": "Author of Dune. The spice must flow."
}

### Delete author (replace id with a real)
DELETE http://localhost:3000/authors/2



### Get all users
GET http://localhost:3000/users 
Accept: application/json

### Create user
POST http://localhost:3000/users    
Content-Type: application/json

{
  "name": "Shai Gilgeous-Alexander",
  "email": "SGA@gmail.com"
}

### Update existing user (replace id with real)
PUT http://localhost:3000/users/2  
Content-Type: application/json

{
  "name": "Shai Gilgeous-Alexander",
  "email": "SGA_MVP@gmail.com"
}

### Delete user (replace id with a real)
DELETE http://localhost:3000/users/2

### Add Book to User
POST http://localhost:3000/users/books
Content-Type: application/json

{
  "userId": 1,
  "bookId": 5
}

### Delete Book from User (replace userId and bookId with real)
DELETE http://localhost:3000/users/1/books/5  

