version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bookapi
      POSTGRES_PASSWORD: bookapi
      POSTGRES_DB: bookapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://bookapi:bookapi@db:5432/bookapi
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      VITE_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: